on: [pull_request]

jobs:
    hello_world_job:
        runs-on: ubuntu-latest
        name: Hello world job
        steps:
            - name: First step
              id: first_step
              uses: rohithpr/gh-action-hello-world@branch-actions
              env:
                event_name: ${{github.event_name}}
