on: [push]

jobs:
    hello_world_job:
        runs-on: ubuntu-latest
        name: Hello world job
        steps:
            - name: First step
              id: first_step
              uses: rohithpr/gh-action-hello-world@0.0.3
            - name: Second step
              run: echo "The time was ${{ steps.first_step.outputs.time }}"
